# Demo
---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    nginx_gateway:
      hosts:
        nginx-gateway:
          ansible_host: 192.168.1.100
          ansible_user: root
    grpc_apps:
      hosts:
        grpc-app-1:
          ansible_host: 192.168.1.101
          ansible_user: root
          grpc_app_name: "grpc-app-1"
        grpc-app-2:
          ansible_host: 192.168.1.102
          ansible_user: root
          grpc_app_name: "grpc-app-2"
